### ISSUE TITLE
Fehlermeldung bei anlegen von MM-Attributen

### ISSUE THREAD

**Issue by tognit** [contao-community-alliance/meta-palettes#31]
Wenn ich bei MM neue attributen anlegen möchte, erhalte ich im Header nachfolgende Fehlermeldung:

```
Warning: Invalid argument supplied for foreach() in composer/vendor/bit3/contao-meta-palettes/src/MetaPalettesBuilder.php on line 214
```

```
Warning: Cannot modify header information - headers already sent by (output started at /system/helper/functions.php:70) in system/modules/core/library/Contao/Template.php on line 298
```

```
Warning: Cannot modify header information - headers already sent by (output started at /system/helper/functions.php:70) in system/modules/core/library/Contao/Template.php on line 299
```

Contao = 3.2.16
MM = dev-tng (8d377fc5) vom 06.01.2015

**Comment by seaneble** [comment]
Confirmed in 
contao/core	3.3.4
contao-community-alliance/meta-palettes	1.9.4

The message appears when viewing attributes for any model (in this case, no attributes are present as it is a freshly created model).
![empty_attributes](https://cloud.githubusercontent.com/assets/1255670/6866175/f76a63c8-d475-11e4-9db9-23a75e9f228f.png)

**Comment by dmolineus** [comment]
This ticket is getting old. Is it still an issue?

**Comment by sleitz** [comment]
Cannot reproduce anymore.
