### ISSUE TITLE
PHP7 Fehler

### ISSUE THREAD

**Issue by BugBuster1701** [contao-community-alliance/meta-palettes#34]
[Zeile](https://github.com/contao-community-alliance/meta-palettes/blob/master/src/MetaPalettes.php#L570) ersetzen

``
$strValue = $this->$callback[0]->$callback[1]($strValue, $dataContainer);
``
in
``
$strValue = $this->{$callback[0]}->{$callback[1]}($strValue, $dataContainer);
``

**Comment by discordier** [comment]
@dmolineus Da du da grad dran bist, machst du dann auch gleich das Release fertig?
Signed tag und ab dafyr.

**Comment by BugBuster1701** [comment]
Da fehlt noch eine Klammer!

**Comment by dmolineus** [comment]
Release 1.10.0 mit PHP 7 und Contao 4 Support ist draußen.
