### ISSUE TITLE
Too much recursion

### ISSUE THREAD

**Issue by richardhj** [contao-community-alliance/meta-palettes#37]
…with v2.0 on calling `contao?do=metamodel`

[contao.pdf](https://github.com/contao-community-alliance/meta-palettes/files/1593107/contao.pdf)
![screen shot 2017-12-29 at 13 43 11](https://user-images.githubusercontent.com/1284725/34437411-40ecb080-ec9e-11e7-92ee-888e8b64c9f8.png)

**Comment by dmolineus** [comment]
Are there any 3rd party extensions in use (going beyond the default mm extension stack)? Never stumbled upon it so far.

Could you provide your composer.lock file?

**Comment by richardhj** [comment]
Caught!

Found the fault in my code.
I wrote 
```$GLOBALS['TL_DCA']['tl_metamodel']['metapalettes']['default extends default']['+advanced'][] = 'myfield';```

This looks like nonsense at the first sight, however, I wanted to save time when I have written my dca. And this was running in v1.0 😇

**Comment by dmolineus** [comment]
Nice idea to extend a default palette. :) V2.0 supports multiple inheritance so it runs in the recursion issue.

As your code worked but never was official supported nor an extension can trust it would work (as it easily would be overwritten) I won't fix it.

Probably add an exception to prevent self inheritance. A circular recursion can't be detected with the current implantation though.

**Comment by dmolineus** [comment]
Now an exception is thrown if a circular reference to the same palette name is detected (See 65fe4a0).

**Comment by richardhj** [comment]
👍
