### ISSUE TITLE
Public state the services

### ISSUE THREAD

**Issue by dmolineus** [contao-community-alliance/meta-palettes#39]
I noticed @baumannsven commit cf91226463f23b46b27fb8607a1dafa6b5aa0049 which made all services public. Actually I don't like the idea. I'm strongly for using DI where possible and do not allow to use the DIC as service locator where not needed for BC reasons.

So could you please explain why you made following services public?
 - cca.meta_palettes.parser
 - cca.meta_palettes.interpreter.string_palettes

All are used as dependencies for the listeners in https://github.com/contao-community-alliance/meta-palettes/blob/master/src/Resources/config/listeners.yml, so I don't see any reason why.

**Comment by baumannsven** [comment]
@dmolineus 
I was not sure what the status of these services should be. If you can assure me that these services do not have to be published, then I will change this.

**Comment by dmolineus** [comment]
Yes, they don't have to. Can't talk of any third party which might uses it, but they are not designed to be public.

**Comment by baumannsven** [comment]
Fixed in 95a6752e95bd51b7b8ec80ed739db3fc80390f06
