### ISSUE TITLE
double section advanced in render settings

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/meta-palettes#42]
double section advanced in render settings

see 
* https://github.com/MetaModels/attribute_file/issues/70
* https://github.com/MetaModels/attribute_translatedfile/issues/25

**Comment by dmolineus** [comment]
Issue is not caused by metapalettes

**Comment by dmolineus** [comment]
Follow to the next issue https://github.com/MetaModels/core/issues/1280
