### ISSUE TITLE
Support Symfony 5?

### ISSUE THREAD

**Issue by Tastaturberuf** [contao-community-alliance/meta-palettes#45]
https://github.com/contao-community-alliance/meta-palettes/blob/20b0c78ad4049a2c2f04156b21f9737b11444761/composer.json#L37-L39

Since [Tag 2.0.1](https://github.com/contao-community-alliance/meta-palettes/tree/2.0.1) works fine with symfony 5.4 we can bump this version up.

**Comment by dmolineus** [comment]
Done with 2.0.8

**Comment by Tastaturberuf** [comment]
thx
