### ISSUE TITLE
Versions since 2.1.0 only for Contao 4.13

### ISSUE THREAD

**Issue by cboelter** [contao-community-alliance/meta-palettes#52]
Since the changes from Version 2.1.1 and 2.1.2 the package requires `doctrine/dbal` in version 3.X. 
This version is only available since Contao 4.13, so the minimum version of Contao should be moved from 4.9 to 4.13.
Currently all my all older installations are installing the latest 2.1.2 and I have to add a conflict to all installation to prevent this.

**Comment by zonky2** [comment]
Version 2 is also possible - https://github.com/contao-community-alliance/meta-palettes/blob/b85af6c76acc6cc580af79bc5518818e6cab25b1/composer.json#L35

**Comment by cboelter** [comment]
@zonky2 thats right, but the function `executeQuery()`is only available since version 3.X of `doctrine/dbal`. 
In older versions of `doctrine/dbal` there is only the `execute()`function.
The version constraint you posted below is the reason why the versions 2.1.1 and 2.1.2 are installable in older versions of contao. I think it would help to remove the `^2.11`.

**Comment by cboelter** [comment]
> > I think it would help to remove the `^2.11`.
> 
> No, that would not help. If you remove that dependency then versions `2.1.1` and `2.1.2` will still be installed in Contao 4.9, which will again cause this error. The only way to fix this is to restore compatibility with `doctrine/dbal` `^2.11`

Oh you are right :-) 

I think the PR #53 should work, maybe if you want I can provide a PR which works with a function_exists or a version check, so there would no deprecated function call in 4.13 and up.

**Comment by dmolineus** [comment]
Fixed with 2.1.3
